<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$config['website_domain'] = 'http://quan.huiyunzhi.cn/';
$config['website_title'] = '商城系统';
$config['website_logo'] = '';
$config['website_keywords'] = '商城系统';
$config['website_desc'] = '商城系统';
$config['website_icp'] = '';
$config['goods_list_pagesize'] = '15';
$config['goods_list_orderby'] = 'up_time';
$config['goods_list_orderby_type'] = 'desc';
$config['cache_type'] = 'file';
$config['share_type'] = '0';
$config['share_one_proportion'] = '10';
$config['share_two_proportion'] = '5';
$config['share_price_type'] = 'balance';
$config['wx_appid'] = 'wx06a15a3cfbd766e5';
$config['wx_secret'] = '419de876cb7765a8b8564ec20b030eef';
$config['miniApp_appid'] = 'wxff5bc8dc04497e1c';
$config['miniApp_secret'] = 'f03b2e904921ac34e796ebe5b223f13e';
$config['wx_flag_sms_tmp_id'] = '';
$config['wx_cashback_sms_tmp_id'] = '';
$config['sms_open'] = '2';
$config['sms_appkey'] = '23423709';
$config['sms_secret'] = 'c16bae135369f45c1cc024922a89b657';
$config['delivery_appid'] = '';
$config['delivery_appkey'] = '';
$config['order_auto_confirm'] = '10080';
$config['order_auto_cancel'] = '2880';
$config['shop_withdraw_commission'] = '10';
$config['goods_store_nums'] = '100';
$config['authentication_string'] = '~!@#$%^&*()_3BYS_BBC_AUTHENTICATION_STRING';

